"""
tests/web/test_board_signer.py -- identity-based board signing (2026-10-04).

Exercises common.board_sign + web.main's _board_auth/board_post with a real
ed25519 key generated by ssh-keygen in a temp dir, against the sqlite twin of
board_signers. The X-Board-Key path must be unchanged.
"""
from __future__ import annotations

import asyncio
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

import pytest
from fastapi import HTTPException

sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))

import web.main as web_main  # noqa: E402
from common import board_sign as bs  # noqa: E402
from common import db  # noqa: E402

pytestmark = pytest.mark.skipif(shutil.which("ssh-keygen") is None, reason="ssh-keygen required")


@pytest.fixture
def keypair(tmp_path):
    k = tmp_path / "k"
    subprocess.run(["ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-C", "alice@laptop", "-f", str(k)], check=True)
    return str(k), (tmp_path / "k.pub").read_text().strip()


@pytest.fixture
def other_keypair(tmp_path):
    k = tmp_path / "other"
    subprocess.run(["ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-C", "mallory@laptop", "-f", str(k)], check=True)
    return str(k), (tmp_path / "other.pub").read_text().strip()


def _req(method="POST", path="/api/v1/board", body: bytes = b"", **headers):
    """Stand-in for starlette's Request with the attributes _board_auth reads."""
    async def _body():
        return body
    p, _, q = path.partition("?")
    return SimpleNamespace(method=method, url=SimpleNamespace(path=p, query=q), headers=headers,
                           body=_body, client=SimpleNamespace(host="127.0.0.1"))


def _signed_headers(priv, method, path, body: bytes, signer="alice", ts=None):
    ts = int(time.time()) if ts is None else ts
    p, _, q = path.partition("?")
    msg = bs.canonical_message(method, p, ts, body, q)
    return {"X-Board-Signer": signer, "X-Board-Timestamp": str(ts),
            "X-Board-Signature": bs.sign_with_ssh_keygen(priv, msg)}


BODY = json.dumps({"from": "whoever", "to": "dispatch", "thread": "coord",
                   "subject": "s", "body": "b"}).encode()


# -- pure verification ---------------------------------------------------------

def test_sshsig_roundtrip_and_tamper(keypair):
    priv, pub = keypair
    msg = bs.canonical_message("POST", "/api/v1/board", 1700000000, b"{}")
    sig = bs.sign_with_ssh_keygen(priv, msg)
    assert bs.verify(pub, sig, msg) is True
    assert bs.verify(pub, sig, msg + b"x") is False


def test_wrong_key_rejected(keypair, other_keypair):
    _, pub = keypair
    opriv, _ = other_keypair
    msg = bs.canonical_message("POST", "/api/v1/board", 1700000000, b"{}")
    assert bs.verify(pub, bs.sign_with_ssh_keygen(opriv, msg), msg) is False


def test_timestamp_window():
    now = 1700000000
    assert bs.check_timestamp(str(now - 299), now) == now - 299
    with pytest.raises(bs.BoardSignError):
        bs.check_timestamp(str(now - 301), now)
    with pytest.raises(bs.BoardSignError):
        bs.check_timestamp("soon", now)


# -- server path --------------------------------------------------------------

def _auth(req, route="POST /api/v1/board", scope=db.BOARD_SCOPE_WRITE, policy=None, fresh=True):
    # policy tests re-present one signed request on purpose; ed25519 is
    # deterministic, so they start from an empty replay cache (U6). The
    # single-use test passes fresh=False.
    if fresh:
        web_main._BOARD_REPLAY._seen.clear()
    with patch.dict(web_main.BOARD_AUTH_POLICY, {route: policy} if policy else {}):
        return asyncio.run(web_main._board_auth(req, route, scope))


def test_signed_request_accepted_and_attributed(keypair):
    priv, pub = keypair
    db.board_signer_upsert("alice", pub, "alice@laptop")
    with patch.object(web_main.db, "board_token_valid", return_value=False):
        req = _req(body=BODY, **_signed_headers(priv, "POST", "/api/v1/board", BODY))
        assert _auth(req) == "alice"


def test_inactive_signer_rejected(keypair):
    priv, pub = keypair
    db.board_signer_upsert("alice", pub, "alice@laptop")
    db.board_signer_set_active("alice", False, "inert")
    with patch.object(web_main.db, "board_token_valid", return_value=False):
        req = _req(body=BODY, **_signed_headers(priv, "POST", "/api/v1/board", BODY))
        with pytest.raises(HTTPException) as e:
            _auth(req)
    assert e.value.status_code == 401 and "inactive" in e.value.detail


def test_stale_timestamp_rejected(keypair):
    priv, pub = keypair
    db.board_signer_upsert("alice", pub, "alice@laptop")
    with patch.object(web_main.db, "board_token_valid", return_value=False):
        req = _req(body=BODY, **_signed_headers(priv, "POST", "/api/v1/board", BODY, ts=int(time.time()) - 900))
        with pytest.raises(HTTPException) as e:
            _auth(req)
    assert e.value.status_code == 401 and "replay" in e.value.detail


def test_body_tamper_rejected(keypair):
    priv, pub = keypair
    db.board_signer_upsert("alice", pub, "alice@laptop")
    with patch.object(web_main.db, "board_token_valid", return_value=False):
        req = _req(body=BODY + b" ", **_signed_headers(priv, "POST", "/api/v1/board", BODY))
        with pytest.raises(HTTPException) as e:
            _auth(req)
    assert e.value.status_code == 401 and "does not verify" in e.value.detail


def test_unknown_signer_rejected(keypair):
    priv, _ = keypair
    with patch.object(web_main.db, "board_token_valid", return_value=False):
        req = _req(body=BODY, **_signed_headers(priv, "POST", "/api/v1/board", BODY, signer="nobody"))
        with pytest.raises(HTTPException) as e:
            _auth(req)
    assert e.value.status_code == 401


def test_policy_either_accepts_key_alone():
    with patch.object(web_main.db, "board_token_valid", return_value=True):
        assert _auth(_req(body=BODY, **{"X-Board-Key": "minted"})) is None


def _minted(ttl_s, revoked=None):
    now = time.time()
    return {"created_at": now - 60, "expires_at": now - 60 + ttl_s, "scope": "board-write",
            "label": "alice", "revoked_at": revoked, "ttl_s": ttl_s}


def test_policy_high_requires_signature_and_time_based_token(keypair):
    """'both' (old name) == 'high': a valid signature AND a MINTED token whose
    lifetime is <= HIGH_TOKEN_MAX_TTL. The master key never qualifies."""
    priv, pub = keypair
    db.board_signer_upsert("alice", pub, "alice@laptop")
    sig_hdrs = _signed_headers(priv, "POST", "/api/v1/board", BODY)
    with patch.object(web_main.db, "board_token_valid", return_value=False), \
            patch.object(web_main.db, "board_token_info", return_value=None):
        with pytest.raises(HTTPException):
            _auth(_req(body=BODY, **sig_hdrs), policy="high")           # signature only
    with patch.object(web_main.db, "board_token_valid", return_value=True), \
            patch.object(web_main.db, "board_token_info", return_value=_minted(3600)):
        with pytest.raises(HTTPException):
            _auth(_req(body=BODY, **{"X-Board-Key": "minted"}), policy="high")   # token only
        assert _auth(_req(body=BODY, **{"X-Board-Key": "minted", **sig_hdrs}), policy="high") == "alice"
        assert _auth(_req(body=BODY, **{"X-Board-Key": "minted", **sig_hdrs}), policy="both") == "alice"   # alias


def test_policy_high_master_key_alone_never_qualifies(keypair):
    priv, pub = keypair
    db.board_signer_upsert("alice", pub, "alice@laptop")
    sig_hdrs = _signed_headers(priv, "POST", "/api/v1/board", BODY)
    # master key: board_token_valid False (not minted), board_token_info None
    with patch.object(web_main, "_BOARD_KEY", "MASTER"), patch.object(web_main.db, "board_token_valid", return_value=False), \
            patch.object(web_main.db, "board_token_info", return_value=None):
        assert _auth(_req(body=BODY, **{"X-Board-Key": "MASTER"}), policy="normal") is None   # normal: fine
        with pytest.raises(HTTPException) as e:
            _auth(_req(body=BODY, **{"X-Board-Key": "MASTER", **sig_hdrs}), policy="high")
    assert "does not qualify" in e.value.detail


def test_policy_high_rejects_long_lived_or_revoked_token(keypair):
    priv, pub = keypair
    db.board_signer_upsert("alice", pub, "alice@laptop")
    sig_hdrs = _signed_headers(priv, "POST", "/api/v1/board", BODY)
    with patch.object(web_main.db, "board_token_valid", return_value=True), \
            patch.object(web_main.db, "board_token_info", return_value=_minted(30 * 86400)):   # 30d read token
        with pytest.raises(HTTPException):
            _auth(_req(body=BODY, **{"X-Board-Key": "minted", **sig_hdrs}), policy="high")
    with patch.object(web_main.db, "board_token_valid", return_value=True), \
            patch.object(web_main.db, "board_token_info", return_value=_minted(3600, revoked=time.time())):
        with pytest.raises(HTTPException):
            _auth(_req(body=BODY, **{"X-Board-Key": "minted", **sig_hdrs}), policy="high")


def _cosign_headers(priv, method, path, body, cosigner, ts):
    p, _, q = path.partition("?")
    msg = bs.canonical_message(method, p, ts, body, q)
    return {"X-Board-Cosigner": cosigner, "X-Board-Cosignature": bs.sign_with_ssh_keygen(priv, msg)}


def test_policy_cosign_requires_admin_cosignature(keypair, other_keypair):
    priv, pub = keypair
    opriv, opub = other_keypair
    db.board_signer_upsert("alice", pub, "alice@laptop", role="member", kind="human")
    db.board_signer_upsert("mallory", opub, "mallory@laptop", role="member", kind="human")
    ts = int(time.time())
    sig_hdrs = _signed_headers(priv, "POST", "/api/v1/board", BODY, ts=ts)
    with patch.object(web_main.db, "board_token_valid", return_value=False):
        with pytest.raises(HTTPException):                                   # signature alone
            _auth(_req(body=BODY, **sig_hdrs), policy="cosign")
        with pytest.raises(HTTPException) as e:                              # member cosigner
            _auth(_req(body=BODY, **sig_hdrs, **_cosign_headers(opriv, "POST", "/api/v1/board", BODY, "mallory", ts)), policy="cosign")
        assert "not an admin" in e.value.detail
        db.board_signer_set_role("mallory", role="admin")
        assert _auth(_req(body=BODY, **sig_hdrs, **_cosign_headers(opriv, "POST", "/api/v1/board", BODY, "mallory", ts)), policy="cosign") == "alice"
        with pytest.raises(HTTPException) as e:                              # self-cosign
            _auth(_req(body=BODY, **sig_hdrs, **_cosign_headers(priv, "POST", "/api/v1/board", BODY, "alice", ts)), policy="cosign")
        assert "differ" in e.value.detail
        db.board_signer_set_active("mallory", False, "inert")                # inert admin cannot cosign
        with pytest.raises(HTTPException):
            _auth(_req(body=BODY, **sig_hdrs, **_cosign_headers(opriv, "POST", "/api/v1/board", BODY, "mallory", ts)), policy="cosign")


def test_deactivate_is_immediate_no_restart(keypair):
    """board_signers.active is re-read on every request: deactivate -> the very
    next request 401s with no restart, and activate restores it."""
    priv, pub = keypair
    db.board_signer_upsert("alice", pub, "alice@laptop")
    hdr = lambda: _signed_headers(priv, "POST", "/api/v1/board", BODY)  # noqa: E731
    with patch.object(web_main.db, "board_token_valid", return_value=False):
        assert _auth(_req(body=BODY, **hdr())) == "alice"
        db.board_signer_set_active("alice", False, "kill")
        with pytest.raises(HTTPException) as e:
            _auth(_req(body=BODY, **hdr()))
        assert e.value.status_code == 401
        db.board_signer_set_active("alice", True)
        assert _auth(_req(body=BODY, **hdr())) == "alice"


def test_roles_and_revocation_helpers(keypair):
    db.init_db()   # audit_log for the revoke helpers' audit() rows
    _, pub = keypair
    db.board_signer_upsert("alice", pub, "alice@laptop", role="admin", kind="human")
    assert db.board_signer_get("alice")["role"] == "admin"
    db.board_signer_upsert("alice", pub, "alice@laptop")           # re-key keeps role
    assert db.board_signer_get("alice")["role"] == "admin"
    with pytest.raises(ValueError):
        db.board_signer_set_role("alice", role="king")
    since = time.time() - 60
    assert db.board_tokens_revoked_since("alice", since) == 0
    tok = db.board_mint_read_token(label="alice")["token"]
    assert db.board_token_info(tok)["label"] == "alice"
    assert db.board_revoke_all_for_account("alice")["board_tokens"] == 1
    assert db.board_tokens_revoked_since("alice", since) == 1
    assert db.board_token_info(tok)["revoked_at"] is not None


def test_policy_key_ignores_signature(keypair):
    priv, pub = keypair
    db.board_signer_upsert("alice", pub, "alice@laptop")
    with patch.object(web_main.db, "board_token_valid", return_value=False):
        with pytest.raises(HTTPException):
            _auth(_req(body=BODY, **_signed_headers(priv, "POST", "/api/v1/board", BODY)), policy="key")


def test_bad_signature_never_downgrades_to_key_path(keypair, other_keypair):
    """A presented-but-wrong signature is a 401 even when a valid key rides along."""
    _, pub = keypair
    opriv, _ = other_keypair
    db.board_signer_upsert("alice", pub, "alice@laptop")
    with patch.object(web_main.db, "board_token_valid", return_value=True):
        hdrs = {"X-Board-Key": "minted", **_signed_headers(opriv, "POST", "/api/v1/board", BODY)}
        with pytest.raises(HTTPException) as e:
            _auth(_req(body=BODY, **hdrs))
    assert e.value.status_code == 401


def test_x_board_key_path_unchanged():
    with patch.object(web_main.db, "board_token_valid", return_value=False):
        with pytest.raises(HTTPException) as e:
            asyncio.run(web_main._board_auth(_req(body=BODY, **{"X-Board-Key": "bogus"}), "POST /api/v1/board"))
    assert e.value.status_code == 401
    with patch.object(web_main.db, "board_token_valid", return_value=True):
        assert asyncio.run(web_main._board_auth(_req(body=BODY, **{"X-Board-Key": "ok"}), "POST /api/v1/board")) is None


def test_board_post_attributes_from_to_signer(keypair):
    priv, pub = keypair
    db.board_signer_upsert("alice", pub, "alice@laptop")
    captured = {}

    def fake_insert(**kw):
        captured.update(kw)
        return {"id": "brd-x", "ts": "2026-10-04T00:00:00Z", "seq": 1}

    msg = web_main.BoardMsgIn(**json.loads(BODY))
    with patch.object(web_main.db, "board_token_valid", return_value=False), \
            patch.object(web_main.db, "board_insert", side_effect=fake_insert), \
            patch.object(web_main, "_scrub_gate", return_value=None):
        req = _req(body=BODY, **_signed_headers(priv, "POST", "/api/v1/board", BODY))
        res = asyncio.run(web_main.board_post(msg, req))
    assert res.status_code == 201
    assert captured["from_side"] == "alice"


# -- U6 (2026-10-04): signed query string + single-use signatures ---------------

def test_query_string_is_signed(keypair):
    priv, pub = keypair
    db.board_signer_upsert("alice", pub, "alice@laptop")
    route = "GET /api/v1/vault/research"
    with patch.object(web_main.db, "board_token_valid", return_value=False):
        h = _signed_headers(priv, "GET", "/api/v1/vault/research?path=A.md", b"")
        assert _auth(_req("GET", "/api/v1/vault/research?path=A.md", b"", **h), route, db.BOARD_SCOPE_READ) == "alice"
        h2 = _signed_headers(priv, "GET", "/api/v1/vault/research?path=A.md", b"")
        with pytest.raises(HTTPException) as e:
            _auth(_req("GET", "/api/v1/vault/research?path=B.md", b"", **h2), route, db.BOARD_SCOPE_READ)
    assert e.value.status_code == 401 and "does not verify" in e.value.detail


def test_signature_is_single_use(keypair):
    priv, pub = keypair
    db.board_signer_upsert("alice", pub, "alice@laptop")
    with patch.object(web_main.db, "board_token_valid", return_value=False):
        h = _signed_headers(priv, "POST", "/api/v1/board", BODY)
        assert _auth(_req(body=BODY, **h)) == "alice"
        with pytest.raises(HTTPException) as e:
            _auth(_req(body=BODY, **h), fresh=False)
    assert e.value.status_code == 401 and "already used" in e.value.detail


def test_replay_cache_expiry_and_cap():
    c = bs.ReplayCache(window=300, max_entries=3)
    assert c.check_and_add("s1", now=1000) and not c.check_and_add("s1", now=1001)
    assert c.check_and_add("s1", now=1000 + 601)          # aged out after 2x window
    for i in range(5):
        c.check_and_add(f"x{i}", now=2000)
    assert len(c._seen) == 3
