-- Migration 0002: SCHEMA (src/common/db.py)
-- Auto-translated from the SQLite schema block of the same name
-- (docs/POSTGRES_MIGRATION.md Appendix A). Tables: audit_log, auth_tokens, cps_scores, feed_state, hot_alerts, metar_snapshot, nas_programs, tfrs, trigger_log
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS, ALTER ... ADD COLUMN IF NOT EXISTS.

-- Feed freshness tracking
CREATE TABLE IF NOT EXISTS feed_state (
    feed_name       TEXT PRIMARY KEY,
    fetched_at      REAL,           -- Unix timestamp
    error           TEXT,           -- NULL on success
    consecutive_failures INTEGER DEFAULT 0,
    payload_hash    TEXT            -- SHA-256 of raw payload (change detection)
);

-- TFRs: raw + enriched
CREATE TABLE IF NOT EXISTS tfrs (
    tfr_id          TEXT PRIMARY KEY,
    raw_json        TEXT NOT NULL,
    enriched_text   TEXT,           -- NULL until tfr-enrichment runs
    enriched_at     REAL,
    effective_start REAL,
    effective_end   REAL,
    is_vip          INTEGER DEFAULT 0,
    notified        INTEGER DEFAULT 0,
    inserted_at     REAL DEFAULT (extract(epoch from now()))
);

-- METAR / weather snapshot (latest only per station)
CREATE TABLE IF NOT EXISTS metar_snapshot (
    station         TEXT PRIMARY KEY,
    raw_metar       TEXT NOT NULL,
    ceiling_ft      INTEGER,
    visibility_sm   REAL,
    wind_kt         INTEGER,
    precip_code     TEXT,           -- RA / SN / TS / etc. — NULL if clear
    obs_time        REAL,
    fetched_at      REAL
);

-- NAS ground stops / GDPs
CREATE TABLE IF NOT EXISTS nas_programs (
    program_id      TEXT PRIMARY KEY,
    type            TEXT,           -- GDP | GS | AAR
    facility        TEXT,
    raw_json        TEXT,
    active          INTEGER DEFAULT 1,
    fetched_at      REAL
);

-- CPS scores (history + latest)
CREATE TABLE IF NOT EXISTS cps_scores (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    computed_at     REAL DEFAULT (extract(epoch from now())),
    score           TEXT NOT NULL,  -- GREEN | YELLOW | RED
    label           TEXT NOT NULL,  -- GO | MARGINAL | NO-GO
    ceiling_factor  TEXT,
    visibility_factor TEXT,
    wind_factor     TEXT,
    precip_factor   TEXT,
    airspace_factor TEXT,
    gdp_factor      TEXT,
    narrative       TEXT
);

-- Route impact narrative (latest)
CREATE TABLE IF NOT EXISTS hot_alerts (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    computed_at     REAL DEFAULT (extract(epoch from now())),
    route_narrative TEXT,
    active_tfrs     TEXT,           -- JSON array of TFR IDs
    vip_flags       TEXT,           -- JSON array of VIP callsigns matched
    source          TEXT DEFAULT 'route'  -- 'route' | 'flight' | 'train'
);

-- Audit log (append-only, Tier 2 actions)
CREATE TABLE IF NOT EXISTS audit_log (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_time      REAL DEFAULT (extract(epoch from now())),
    action          TEXT NOT NULL,
    tier            TEXT NOT NULL,
    token_prefix    TEXT,           -- First 8 chars of token (never full token)
    remote_addr     TEXT,
    detail          TEXT            -- JSON
);

-- Issued auth tokens (hash stored, never plaintext)
CREATE TABLE IF NOT EXISTS auth_tokens (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash      TEXT UNIQUE NOT NULL,
    token_prefix    TEXT NOT NULL,  -- ctdc_<user>_ prefix for display
    user_label      TEXT NOT NULL,
    tier            TEXT NOT NULL,  -- cert | shares | admin
    device_label    TEXT,
    created_at      REAL DEFAULT (extract(epoch from now())),
    expires_at      REAL,           -- NULL = no expiry
    revoked_at      REAL            -- NULL = active
);

-- Trigger queue (admin mutations)
CREATE TABLE IF NOT EXISTS trigger_log (
    id              TEXT PRIMARY KEY,   -- UUID
    trigger_type    TEXT NOT NULL,
    payload         TEXT,               -- JSON
    queued_at       REAL DEFAULT (extract(epoch from now())),
    outcome         TEXT DEFAULT 'in_flight',   -- in_flight | success | failed
    resolved_at     REAL,
    error_msg       TEXT
);
