-- Migration 0003: SCHEMA_V2 (src/common/db.py)
-- Auto-translated from the SQLite schema block of the same name
-- (docs/POSTGRES_MIGRATION.md Appendix A). Tables: amtrak_status, notams, nws_alerts, nws_forecast, ops_plan
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS, ALTER ... ADD COLUMN IF NOT EXISTS.

-- FAA NOTAMs
CREATE TABLE IF NOT EXISTS notams (
    notam_id        TEXT PRIMARY KEY,
    raw_json        TEXT NOT NULL,
    facility        TEXT,
    classification  TEXT,           -- NOTAM-D, FDC, POINTER, etc.
    effective_start REAL,
    effective_end   REAL,
    text_body       TEXT,
    inserted_at     REAL DEFAULT (extract(epoch from now()))
);

-- NWS active hazardous weather alerts (DC/MD/VA)
CREATE TABLE IF NOT EXISTS nws_alerts (
    alert_id        TEXT PRIMARY KEY,
    event_type      TEXT,           -- Winter Storm Warning, Tornado Watch, etc.
    area_desc       TEXT,
    severity        TEXT,           -- Extreme / Severe / Moderate / Minor
    certainty       TEXT,
    effective       REAL,
    expires         REAL,
    headline        TEXT,
    description     TEXT,
    fetched_at      REAL DEFAULT (extract(epoch from now()))
);

-- NWS zone forecast (latest only per zone)
CREATE TABLE IF NOT EXISTS nws_forecast (
    zone            TEXT PRIMARY KEY,
    forecast_json   TEXT,
    fetched_at      REAL DEFAULT (extract(epoch from now()))
);

-- Amtrak status for DC-area trains
CREATE TABLE IF NOT EXISTS amtrak_status (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fetched_at      REAL DEFAULT (extract(epoch from now())),
    trains_json     TEXT,           -- JSON array of train status objects
    delay_summary   TEXT            -- Human-readable delay summary
);

-- Ops plan (operator-populated scheduled trips)
CREATE TABLE IF NOT EXISTS ops_plan (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_date       TEXT,           -- YYYY-MM-DD
    raw_json        TEXT,           -- Full plan JSON
    trip_count      INTEGER,
    loaded_at       REAL DEFAULT (extract(epoch from now()))
);
