-- Migration 0004: SCHEMA_V3 (src/common/db.py)
-- Auto-translated from the SQLite schema block of the same name
-- (docs/POSTGRES_MIGRATION.md Appendix A). Tables: atcscc_opsplan, runsheet, watchlist_sessions
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS, ALTER ... ADD COLUMN IF NOT EXISTS.

-- Daily runsheet (scheduled trips for a given calendar day)
CREATE TABLE IF NOT EXISTS runsheet (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_date        TEXT NOT NULL,      -- YYYY-MM-DD
    scheduled_trips TEXT,               -- JSON array of trip objects
    trip_count      INTEGER DEFAULT 0,
    loaded_at       REAL DEFAULT (extract(epoch from now()))
);

-- Watchlist sessions — flight, train, or custom subject monitoring
-- Active sessions are polled each cycle; terminated sessions write summary to runsheet
CREATE TABLE IF NOT EXISTS watchlist_sessions (
    id              TEXT PRIMARY KEY,   -- UUID
    session_type    TEXT NOT NULL,      -- 'flight' | 'train' | 'custom'
    subject         TEXT NOT NULL,      -- Flight number, train ID, tail number, etc.
    run_date        TEXT NOT NULL,      -- YYYY-MM-DD — links to runsheet
    status          TEXT DEFAULT 'active',  -- 'active' | 'terminated'
    started_at      REAL DEFAULT (extract(epoch from now())),
    terminated_at   REAL,
    session_data    TEXT,               -- JSON — accumulated poll results
    terminal_summary TEXT              -- Plain text summary written on termination
);

-- ATCSCC daily ops plan snapshot (kept indefinitely — pattern analysis)
CREATE TABLE IF NOT EXISTS atcscc_opsplan (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_date       TEXT NOT NULL,      -- YYYY-MM-DD
    nas_programs    TEXT,               -- JSON — GDP/GS/AAR snapshot for the day
    notam_count     INTEGER DEFAULT 0,
    active_airports TEXT,               -- JSON array of affected airports
    pattern_tags    TEXT,               -- JSON array: ['weather-gdp','volume-delay',...]
    weather_summary TEXT,               -- Brief METAR summary at time of snapshot
    fetched_at      REAL DEFAULT (extract(epoch from now()))
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_atcscc_opsplan_date
    ON atcscc_opsplan(plan_date);
