-- Migration 0006: SCHEMA_V5 (src/common/db.py)
-- Auto-translated from the SQLite schema block of the same name
-- (docs/POSTGRES_MIGRATION.md Appendix A). Tables: surface_tracks, swim_alerts, terminal_tracks, watchlist_entries, watchlist_history
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS, ALTER ... ADD COLUMN IF NOT EXISTS.

-- ASDE-X surface movement tracks from SMES (STDDS)
CREATE TABLE IF NOT EXISTS surface_tracks (
    track_id        TEXT NOT NULL,
    airport         TEXT NOT NULL,
    callsign        TEXT,
    squawk          TEXT,
    aircraft_type   TEXT,
    target_type     TEXT,
    latitude        REAL NOT NULL,
    longitude       REAL NOT NULL,
    altitude_ft     REAL,
    speed_kts       INTEGER,
    heading_deg     REAL,
    eram_gufi       TEXT,
    last_seen       TEXT NOT NULL,
    PRIMARY KEY (airport, track_id)
);

-- Terminal radar tracks from TAIS (PCT TRACON via STDDS)
CREATE TABLE IF NOT EXISTS terminal_tracks (
    track_id        TEXT NOT NULL,
    facility        TEXT NOT NULL,
    callsign        TEXT,
    squawk          TEXT,
    mode_s          TEXT,
    latitude        REAL,
    longitude       REAL,
    altitude_ft     REAL,
    ground_speed    INTEGER,
    last_seen       TEXT NOT NULL,
    PRIMARY KEY (facility, track_id)
);

-- SWIM POTUS/VIP hot alerts from FDPS Marine One detection
-- alert_type is PRIMARY KEY: INSERT OR REPLACE keeps only the latest per type.
CREATE TABLE IF NOT EXISTS swim_alerts (
    alert_type      TEXT PRIMARY KEY,
    payload         TEXT,           -- JSON
    expires_at      TEXT NOT NULL   -- ISO 8601
);

-- Active watchlist entries (permanent + transient, both live here)
CREATE TABLE IF NOT EXISTS watchlist_entries (
    id                  TEXT PRIMARY KEY,
    entry_type          TEXT NOT NULL,   -- "flight" | "train"
    tier                TEXT NOT NULL,   -- "permanent" | "transient"
    identifier          TEXT NOT NULL,
    origin              TEXT,
    destination         TEXT,
    route_name          TEXT,
    scheduled_departure TEXT,
    scheduled_arrival   TEXT,
    auto_remove_at      TEXT,            -- NULL for permanent
    added_at            TEXT NOT NULL,
    added_by            TEXT NOT NULL,
    notes               TEXT,
    last_event_at       TEXT,
    last_event_summary  TEXT
);
CREATE INDEX IF NOT EXISTS idx_watchlist_entries_type
    ON watchlist_entries(entry_type);
CREATE INDEX IF NOT EXISTS idx_watchlist_entries_ident
    ON watchlist_entries(identifier);

-- Event log: alert_fired, auto_expired, manual_removed, permanent_removed
CREATE TABLE IF NOT EXISTS watchlist_history (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id        TEXT NOT NULL,
    entry_type      TEXT NOT NULL,
    identifier      TEXT NOT NULL,
    event_type      TEXT NOT NULL,
    event_summary   TEXT,
    event_detail    TEXT,           -- JSON
    fired_at        TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_watchlist_history_entry
    ON watchlist_history(entry_id);
