-- Migration 0009: SCHEMA_V7 (src/common/db.py)
-- Auto-translated from the SQLite schema block of the same name
-- (docs/POSTGRES_MIGRATION.md Appendix A). Tables: acars_messages, local_aircraft, local_airspace_alerts
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS, ALTER ... ADD COLUMN IF NOT EXISTS.

-- Aircraft seen by local UltraFeeder ADS-B receiver.
-- One row per ICAO hex, updated in-place on each position report.
CREATE TABLE IF NOT EXISTS local_aircraft (
    icao_hex        TEXT PRIMARY KEY,
    callsign        TEXT,
    registration    TEXT,
    aircraft_type   TEXT,
    operator        TEXT,
    latitude        REAL,
    longitude       REAL,
    altitude_ft     INTEGER,
    ground_speed    INTEGER,
    track_deg       REAL,
    squawk          TEXT,
    on_ground       INTEGER DEFAULT 0,
    rssi            REAL,
    distance_nm     REAL,
    last_seen       TEXT NOT NULL,
    first_seen      TEXT NOT NULL,
    source          TEXT DEFAULT 'ultrafeeder'
);

-- ACARS messages decoded by acarsdec and routed through acarsrouter.
CREATE TABLE IF NOT EXISTS acars_messages (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    received_at         TEXT NOT NULL,
    freq_mhz            REAL,
    icao_hex            TEXT,
    tail                TEXT,
    flight              TEXT,
    msg_type            TEXT,
    label               TEXT,
    block_id            TEXT,
    ack                 TEXT,
    mode                TEXT,
    msg_text            TEXT,
    raw                 TEXT,
    watchlist_hit       INTEGER DEFAULT 0,
    watchlist_entry_id  TEXT
);

-- Local airspace proximity and emergency alerts (separate from watchlist_history).
CREATE TABLE IF NOT EXISTS local_airspace_alerts (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fired_at            TEXT NOT NULL,
    alert_type          TEXT NOT NULL,
    icao_hex            TEXT,
    callsign            TEXT,
    registration        TEXT,
    distance_nm         REAL,
    altitude_ft         INTEGER,
    squawk              TEXT,
    watchlist_entry_id  TEXT,
    payload             TEXT,
    ntfy_fired          INTEGER DEFAULT 0
);
