-- Migration 0011: SCHEMA_V9 (src/common/db.py)
-- Auto-translated from the SQLite schema block of the same name
-- (docs/POSTGRES_MIGRATION.md Appendix A). Tables: brief_archive
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS, ALTER ... ADD COLUMN IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS brief_archive (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generated_at TEXT NOT NULL,          -- ISO-8601 UTC
    brief_type   TEXT NOT NULL DEFAULT 'ops',  -- 'ops' | 'daily'
    content      TEXT NOT NULL,
    source       TEXT NOT NULL DEFAULT 'skill'  -- 'skill' | 'manual'
);
CREATE INDEX IF NOT EXISTS idx_brief_archive_ts ON brief_archive (generated_at DESC);
