-- Migration 0012: SCHEMA_V10 (src/common/db.py)
-- Auto-translated from the SQLite schema block of the same name
-- (docs/POSTGRES_MIGRATION.md Appendix A). Tables: osint_items, osint_scopes
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS, ALTER ... ADD COLUMN IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS osint_scopes (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label           TEXT    NOT NULL,
    scope_type      TEXT    NOT NULL DEFAULT 'keyword',
    query_terms     TEXT    NOT NULL,
    feed_urls       TEXT    NOT NULL DEFAULT '',
    push_threshold  TEXT    NOT NULL DEFAULT 'HIGH',
    enabled         INTEGER NOT NULL DEFAULT 1,
    created_at      REAL    NOT NULL
);

CREATE TABLE IF NOT EXISTS osint_items (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_id        INTEGER REFERENCES osint_scopes(id) ON DELETE CASCADE,
    title           TEXT    NOT NULL,
    url             TEXT    NOT NULL,
    source_name     TEXT,
    published_at    REAL,
    ingested_at     REAL    NOT NULL,
    score           INTEGER NOT NULL DEFAULT 0,
    score_label     TEXT    NOT NULL DEFAULT 'LOW',
    narrative       TEXT,
    pushed_at       REAL,
    content_hash    TEXT    UNIQUE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_osint_items_scope
    ON osint_items(scope_id);
CREATE INDEX IF NOT EXISTS idx_osint_items_score
    ON osint_items(score DESC);
CREATE INDEX IF NOT EXISTS idx_osint_items_ingested
    ON osint_items(ingested_at DESC);
