-- Migration 0013: SCHEMA_V12 (src/common/db.py)
-- Auto-translated from the SQLite schema block of the same name
-- (docs/POSTGRES_MIGRATION.md Appendix A). Tables: wpc_discussions
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS, ALTER ... ADD COLUMN IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS wpc_discussions (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    awips_id        TEXT NOT NULL,
    product_label   TEXT NOT NULL,
    issued_at       REAL NOT NULL,
    fetched_at      REAL DEFAULT (extract(epoch from now())),
    body            TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_wpc_discussions_awips
    ON wpc_discussions(awips_id, issued_at DESC);
