-- Migration 0015: SCHEMA_V14 (src/common/db.py)
-- Auto-translated from the SQLite schema block of the same name
-- (docs/POSTGRES_MIGRATION.md Appendix A). Tables: webhook_events
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS, ALTER ... ADD COLUMN IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS webhook_events (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source          TEXT    NOT NULL,   -- 'limoanywhere' | 'ringcentral' | '3cx'
    event_type      TEXT    NOT NULL,
    external_ref    TEXT,               -- source's own event/reservation/call id
    payload         TEXT    NOT NULL,   -- raw JSON as received
    received_at     REAL    NOT NULL DEFAULT (extract(epoch from now()))
);
CREATE INDEX IF NOT EXISTS idx_webhook_events_source
    ON webhook_events(source, received_at);
CREATE INDEX IF NOT EXISTS idx_webhook_events_ref
    ON webhook_events(external_ref);
