-- Migration 0016: SCHEMA_V15 (src/common/db.py)
-- Auto-translated from the SQLite schema block of the same name
-- (docs/POSTGRES_MIGRATION.md Appendix A). Tables: international_aviation_feed
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS, ALTER ... ADD COLUMN IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS international_aviation_feed (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source          TEXT    NOT NULL,   -- 'eurocontrol' | 'jasdat'
    record_type     TEXT    NOT NULL,   -- 'notam' | 'sigmet' | 'flow_measure' | etc.
    external_ref    TEXT,
    raw_json        TEXT    NOT NULL,
    fetched_at      REAL    NOT NULL DEFAULT (extract(epoch from now()))
);
CREATE INDEX IF NOT EXISTS idx_intl_aviation_source
    ON international_aviation_feed(source, fetched_at);
