-- Migration 0025: SCHEMA_V26 (src/common/db.py)
-- Auto-translated from the SQLite schema block of the same name
-- (docs/POSTGRES_MIGRATION.md Appendix A). Tables: train_events, vessel_events
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS, ALTER ... ADD COLUMN IF NOT EXISTS.

-- 2026-07-28: train_events + vessel_events -- structured historical
-- accumulation tables, same role for trains/vessels that flight_events
-- plays for flights. Operator request: bring these two verticals up to
-- parity with the flight codeshare/route-lock work (same route-lock +
-- schedule-drift analysis, applied to Amtrak trains and DC-area AIS
-- vessel traffic -- water taxis, cruise ships).
CREATE TABLE IF NOT EXISTS train_events (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    train_number    TEXT,
    train_name      TEXT,
    route_name      TEXT,
    direction       TEXT,
    origin          TEXT,
    destination     TEXT,
    station_code    TEXT,
    station_name    TEXT,
    scheduled_time  TEXT,
    estimated_time  TEXT,
    status          TEXT,
    delay_minutes   INTEGER,
    platform        TEXT,
    fetched_at      REAL DEFAULT (extract(epoch from now()))
);
CREATE INDEX IF NOT EXISTS idx_train_events_number
    ON train_events(train_number, fetched_at);
CREATE INDEX IF NOT EXISTS idx_train_events_number_station
    ON train_events(train_number, station_code, fetched_at);

CREATE TABLE IF NOT EXISTS vessel_events (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mmsi        TEXT,
    name        TEXT,
    lat         REAL,
    lon         REAL,
    sog         REAL,
    cog         REAL,
    hdg         REAL,
    nav_status  TEXT,
    ship_type   TEXT,
    source      TEXT,
    fetched_at  REAL DEFAULT (extract(epoch from now()))
);
CREATE INDEX IF NOT EXISTS idx_vessel_events_mmsi
    ON vessel_events(mmsi, fetched_at);
