-- Migration 0028: SCHEMA_V30 (src/common/db.py)
-- Auto-translated from the SQLite schema block of the same name
-- (docs/POSTGRES_MIGRATION.md Appendix A). Tables: stdds_safety_status_history
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS, ALTER ... ADD COLUMN IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS stdds_safety_status_history (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airport           TEXT NOT NULL,
    control           TEXT,
    previous_bitmask  TEXT,
    new_bitmask       TEXT NOT NULL,
    changed_at        TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_stdds_safety_status_history_airport_time
    ON stdds_safety_status_history(airport, changed_at);
