-- Migration 0039: SCHEMA_V44 (src/common/db.py)
-- Auto-translated from the SQLite schema block of the same name
-- (docs/POSTGRES_MIGRATION.md Appendix A). Tables: metar_history, stdds_rvr_history
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS, ALTER ... ADD COLUMN IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS stdds_rvr_history (
    id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airport                   TEXT NOT NULL,
    runway                    TEXT NOT NULL,
    touchdown_rvr_ft          INTEGER,
    touchdown_trend           TEXT,
    midpoint_rvr_ft           INTEGER,
    midpoint_trend            TEXT,
    rollout_rvr_ft            INTEGER,
    rollout_trend             TEXT,
    edge_light_setting        TEXT,
    centerline_light_setting  TEXT,
    recorded_at               TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_stdds_rvr_history_airport_runway_time
    ON stdds_rvr_history(airport, runway, recorded_at);

CREATE TABLE IF NOT EXISTS metar_history (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station         TEXT NOT NULL,
    raw_metar       TEXT NOT NULL,
    ceiling_ft      INTEGER,
    visibility_sm   REAL,
    wind_kt         INTEGER,
    wind_dir_deg    INTEGER,
    precip_code     TEXT,
    obs_time        REAL,
    recorded_at     REAL NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_metar_history_station_time
    ON metar_history(station, recorded_at);
