-- Migration 0040: SCHEMA_SWIM_V41 (src/common/db_swim.py)
-- Auto-translated from the SQLite schema block of the same name
-- (docs/POSTGRES_MIGRATION.md Appendix A). Tables: datis_snapshots, fdps_destination_changes, flight_events, stdds_rvr, tdes_departure_events, tdls_messages, tfms_edct_slots
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS, ALTER ... ADD COLUMN IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS stdds_rvr (
    airport                  TEXT NOT NULL,
    runway                   TEXT NOT NULL,
    touchdown_rvr_ft         INTEGER,
    touchdown_trend          TEXT,
    midpoint_rvr_ft          INTEGER,
    midpoint_trend           TEXT,
    rollout_rvr_ft           INTEGER,
    rollout_trend            TEXT,
    edge_light_setting       TEXT,
    centerline_light_setting TEXT,
    last_seen                TEXT NOT NULL,
    PRIMARY KEY (airport, runway)
);

CREATE TABLE IF NOT EXISTS tdes_departure_events (
    airport                  TEXT NOT NULL,
    callsign                 TEXT NOT NULL,
    event_time               TEXT NOT NULL,
    beacon_code              TEXT,
    aircraft_type            TEXT,
    computer_id              TEXT,
    clearance_delivery_time  TEXT,
    parking_gate             TEXT,
    eram_gufi                TEXT,
    sfdps_gufi               TEXT,
    destination_airport      TEXT,
    last_seen                TEXT NOT NULL,
    PRIMARY KEY (airport, callsign, event_time)
);

CREATE TABLE IF NOT EXISTS tdls_messages (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airport              TEXT NOT NULL,
    callsign             TEXT,
    message_time         TEXT,
    beacon_code          TEXT,
    aircraft_type        TEXT,
    computer_id          TEXT,
    data_header          TEXT,
    data_body            TEXT,
    eram_gufi            TEXT,
    sfdps_gufi           TEXT,
    destination_airport  TEXT,
    received_at          TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tdls_messages_airport_received
    ON tdls_messages(airport, received_at);
CREATE INDEX IF NOT EXISTS idx_tdls_messages_callsign
    ON tdls_messages(callsign);

CREATE TABLE IF NOT EXISTS datis_snapshots (
    airport     TEXT PRIMARY KEY,
    atis_code   TEXT,
    edit_type   TEXT,
    datis_time  TEXT,
    body        TEXT,
    last_seen   TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tfms_edct_slots (
    control_element              TEXT NOT NULL,
    aircraft_id                  TEXT NOT NULL,
    control_type                 TEXT,
    program_parameter            TEXT,
    delay_mode                   TEXT,
    departure_airport            TEXT,
    arrival_airport              TEXT,
    slot_time                    TEXT,
    controlled_departure_time    TEXT,
    controlled_arrival_time      TEXT,
    controlled_departure_iso     TEXT,
    exempt_flag                  INTEGER,
    cancel_flag                  INTEGER,
    slot_hold_flag               INTEGER,
    earliest_arrival_or_entry    TEXT,
    initial_gate_departure_time  TEXT,
    report_time                  TEXT,
    last_seen                    TEXT NOT NULL,
    PRIMARY KEY (control_element, aircraft_id)
);

CREATE TABLE IF NOT EXISTS fdps_destination_changes (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id        TEXT NOT NULL,
    callsign         TEXT,
    origin           TEXT,
    old_destination  TEXT NOT NULL,
    new_destination  TEXT NOT NULL,
    source           TEXT,
    detected_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_fdps_dest_changes_detected
    ON fdps_destination_changes(detected_at);

ALTER TABLE flight_events ADD COLUMN IF NOT EXISTS squawk TEXT;
ALTER TABLE flight_events ADD COLUMN IF NOT EXISTS registration TEXT;
ALTER TABLE flight_events ADD COLUMN IF NOT EXISTS controlling_facility TEXT;
