-- Migration 0042: SCHEMA_SWIM_V44 (src/common/db_swim.py)
-- Auto-translated from the SQLite schema block of the same name
-- (docs/POSTGRES_MIGRATION.md Appendix A). Tables: fdps_diversion_continuations
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS, ALTER ... ADD COLUMN IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS fdps_diversion_continuations (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    change_id               INTEGER,
    diverted_flight_id      TEXT NOT NULL,
    continuation_flight_id  TEXT NOT NULL,
    callsign                TEXT,
    continuation_callsign   TEXT,
    match_basis             TEXT NOT NULL,
    registration            TEXT,
    origin                  TEXT,
    original_destination    TEXT NOT NULL,
    diversion_airport       TEXT NOT NULL,
    acars_msg_id            INTEGER,
    confidence              TEXT NOT NULL,
    diversion_detected_at   TEXT,
    detected_at             TEXT NOT NULL,
    UNIQUE (diverted_flight_id, continuation_flight_id)
);
CREATE INDEX IF NOT EXISTS idx_fdps_div_cont_detected
    ON fdps_diversion_continuations(detected_at);
