-- Migration 0044: SCHEMA_SWIM_V46 (src/common/db_swim.py)
-- Auto-translated from the SQLite schema block of the same name
-- (docs/POSTGRES_MIGRATION.md Appendix A). Tables: fdps_route_versions, tfms_plan_removals
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS, ALTER ... ADD COLUMN IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS tfms_plan_removals (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    callsign          TEXT NOT NULL,
    igtd              TEXT NOT NULL DEFAULT '',
    carrier           TEXT,
    origin            TEXT,
    destination       TEXT,
    flight_ref        TEXT,
    removed_at        TEXT,
    removal_trigger   TEXT,
    kind              TEXT NOT NULL,
    source_facility   TEXT,
    filed_lead_h      REAL,
    origin_surveilled INTEGER NOT NULL DEFAULT 0,
    evidence          TEXT NOT NULL DEFAULT '{}',
    detected_at       TEXT NOT NULL,
    confirmed_at      TEXT,
    reinstated_at     TEXT,
    notified_at       TEXT,
    UNIQUE (callsign, igtd, origin, destination)
);
CREATE INDEX IF NOT EXISTS idx_tfms_plan_removals_detected
    ON tfms_plan_removals(detected_at);
CREATE INDEX IF NOT EXISTS idx_tfms_plan_removals_pending
    ON tfms_plan_removals(confirmed_at, reinstated_at, kind);

CREATE TABLE IF NOT EXISTS fdps_route_versions (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id     TEXT NOT NULL,
    callsign      TEXT,
    origin        TEXT,
    destination   TEXT,
    route_text    TEXT NOT NULL,
    source        TEXT,
    version_num   INTEGER NOT NULL,
    change_class  TEXT,
    eta_first     TEXT,
    eta_last      TEXT,
    eta_delta_min REAL,
    first_seen    TEXT NOT NULL,
    last_seen     TEXT NOT NULL,
    times_seen    INTEGER NOT NULL DEFAULT 1,
    UNIQUE (flight_id, route_text)
);
CREATE INDEX IF NOT EXISTS idx_fdps_route_versions_flight
    ON fdps_route_versions(flight_id, version_num);
