-- Migration 0045: SCHEMA_SWIM_V47 (src/common/db_swim.py)
-- Auto-translated from the SQLite schema block of the same name
-- (docs/POSTGRES_MIGRATION.md Appendix A). Tables: convective_sigmet_archive
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS, ALTER ... ADD COLUMN IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS convective_sigmet_archive (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sigmet_id        TEXT NOT NULL,
    airsigmet_type   TEXT,
    hazard           TEXT NOT NULL,
    severity         INTEGER,
    altitude_low_ft  INTEGER,
    altitude_high_ft INTEGER,
    issued_at        TEXT,
    valid_from       TEXT,
    valid_to         TEXT,
    movement_dir_deg INTEGER,
    movement_spd_kt  INTEGER,
    polygon          TEXT NOT NULL,
    raw_text         TEXT,
    first_seen       TEXT NOT NULL,
    UNIQUE (sigmet_id, valid_from)
);
CREATE INDEX IF NOT EXISTS idx_convective_sigmet_archive_window
    ON convective_sigmet_archive(valid_from, valid_to);
