-- Migration 0047: pull_path_status + board_messages
-- Hand-translated -- these tables are NOT defined via any SCHEMA_V*
-- executescript block. src/common/db.py defines them lazily, inline,
-- via _ensure_pull_path_status(c)/_ensure_board(c), called defensively
-- at the top of every accessor function that touches them, independent
-- of the init_db_vN() chain entirely. docs/POSTGRES_MIGRATION.md's
-- "19 executescript blocks" inventory does not cover this pattern --
-- noted as a drift finding in the Phase 1 handoff.
-- Tables: pull_path_status, board_messages
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS pull_path_status (
    feed_name   TEXT PRIMARY KEY,
    checked_at  REAL,
    ok          INTEGER,   -- 1 = pull path viable, 0 = failed
    state       TEXT,      -- verified|auth_gated|rate_limited|degraded|failed
    http_code   INTEGER,
    latency_ms  INTEGER,
    detail      TEXT
);

CREATE TABLE IF NOT EXISTS board_messages (
    seq         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id          TEXT UNIQUE NOT NULL,
    ts          TEXT NOT NULL,        -- UTC ISO
    from_side   TEXT,
    to_side     TEXT,
    thread      TEXT NOT NULL,
    subject     TEXT,
    body        TEXT,
    refs        TEXT,                 -- JSON array
    in_reply_to TEXT,
    remote_addr TEXT
);
CREATE INDEX IF NOT EXISTS idx_board_thread_seq ON board_messages(thread, seq);
