-- Migration 0052: CIFP reference tables (was SQLite-only per
-- docs/POSTGRES_MIGRATION.md §2's original "11 reference tables stay
-- SQLite forever" call).
--
-- Reversed 2026-09-19 under that same section's own stated exception:
-- "a reference table that a write-path query needs to JOIN gets copied
-- into Postgres too." Geometric reasoning's Phase 0 (assign_geometry())
-- JOINs cifp_fixes/cifp_procedure_legs against flight_events for
-- fix-proximity and route-leg correlation -- this is that JOIN
-- materializing, not a policy override.
--
-- Auto-translated from src/common/cifp_lookup.py's SQLite schema
-- (loaded via docs/CIFP data files, rebuilt on a 28-day AIRAC cycle).
-- REAL -> DOUBLE PRECISION directly (not REAL) per the lesson in 0050:
-- SQLite REAL is always 8-byte IEEE-754, so lat/lon here get the same
-- fix up front instead of a follow-on widening migration.
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS cifp_fixes (
    ident           TEXT    NOT NULL,
    icao_region     TEXT    NOT NULL,
    type            TEXT    NOT NULL,
    lat             DOUBLE PRECISION NOT NULL,
    lon             DOUBLE PRECISION NOT NULL,
    name            TEXT,
    parent_airport  TEXT,
    cycle           TEXT    NOT NULL,
    PRIMARY KEY (ident, icao_region)
);
CREATE INDEX IF NOT EXISTS idx_cifp_fixes_ident
    ON cifp_fixes(ident);

CREATE TABLE IF NOT EXISTS cifp_holds (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airport                 TEXT    NOT NULL,
    proc_type               TEXT    NOT NULL,
    procedure               TEXT    NOT NULL,
    transition              TEXT,
    seq                     INTEGER NOT NULL,
    fix                     TEXT    NOT NULL,
    fix_type                TEXT,
    lat                     DOUBLE PRECISION,
    lon                     DOUBLE PRECISION,
    hold_type               TEXT    NOT NULL,
    hold_meaning            TEXT    NOT NULL,
    turn_direction          TEXT,
    inbound_course_mag      DOUBLE PRECISION,
    leg_time_min            DOUBLE PRECISION,
    leg_dist_nm             DOUBLE PRECISION,
    alt_desc                TEXT,
    alt1                    TEXT,
    alt2                    TEXT,
    speed_limit             TEXT,
    cycle                   TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_cifp_holds_fix
    ON cifp_holds(fix);
CREATE INDEX IF NOT EXISTS idx_cifp_holds_airport
    ON cifp_holds(airport);

CREATE TABLE IF NOT EXISTS cifp_procedure_legs (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airport         TEXT    NOT NULL,
    proc_type       TEXT    NOT NULL,
    procedure       TEXT    NOT NULL,
    transition      TEXT    NOT NULL,
    seq             INTEGER NOT NULL,
    fix             TEXT,
    fix_region      TEXT,
    fix_type        TEXT,
    path_term       TEXT    NOT NULL,
    turn            TEXT,
    lat             DOUBLE PRECISION,
    lon             DOUBLE PRECISION,
    alt_desc        TEXT,
    alt1            TEXT,
    alt2            TEXT,
    speed_limit     TEXT,
    cycle           TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_cifp_legs_lookup
    ON cifp_procedure_legs(airport, proc_type, procedure, transition, seq);

CREATE TABLE IF NOT EXISTS cifp_meta (
    key             TEXT    PRIMARY KEY,
    value           TEXT    NOT NULL
);
