-- Migration 0054: OpenSky registry + codeshare_map -- same reversal and
-- rationale as 0052/0053's headers.
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS opensky_aircraft_registry (
    icao24              TEXT    PRIMARY KEY,
    registration        TEXT,
    manufacturer_icao   TEXT,
    manufacturer_name   TEXT,
    model               TEXT,
    typecode            TEXT,
    serial_number       TEXT,
    icao_aircraft_type  TEXT,
    operator            TEXT,
    operator_icao       TEXT,
    operator_iata       TEXT,
    owner               TEXT,
    registered          TEXT,
    reg_until           TEXT,
    status              TEXT,
    built               TEXT,
    updated_at          DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_opensky_reg_registration
    ON opensky_aircraft_registry(registration);
CREATE INDEX IF NOT EXISTS idx_opensky_registry_icao24_lower
    ON opensky_aircraft_registry(LOWER(icao24));
CREATE INDEX IF NOT EXISTS idx_opensky_registry_registration_upper_nodash
    ON opensky_aircraft_registry(UPPER(REPLACE(registration, '-', '')));

CREATE TABLE IF NOT EXISTS opensky_registry_meta (
    key             TEXT    PRIMARY KEY,
    value           TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS codeshare_map (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marketing_carrier       TEXT    NOT NULL,
    marketing_flight_num    TEXT,
    operating_carrier       TEXT,
    operating_flight_num    TEXT,
    origin                  TEXT,
    destination             TEXT,
    confidence              INTEGER DEFAULT 1,
    source                  TEXT,
    first_seen_at           TEXT,
    last_confirmed_at       TEXT
);
CREATE INDEX IF NOT EXISTS idx_codeshare_marketing
    ON codeshare_map(marketing_carrier, marketing_flight_num);
CREATE INDEX IF NOT EXISTS idx_codeshare_operating
    ON codeshare_map(operating_carrier, operating_flight_num);
