-- Migration 0055: second-brain vault index + semantic layer
-- (was /var/lib/corporatetraveldc/second_brain_index.db, SQLite --
-- never previously in scope for the Postgres cutover since it's a
-- separate store from the dispatch write path).
--
-- Reversed 2026-09-19 for the same JOIN-driven reason as 0052-0054:
-- geometric reasoning's Phase 0 backfill is a sustained writer against
-- semantic_note_derivations while the second-brain poller skills
-- (semantic_compile_daily, entity_tracking_digest, board_sweep, ...)
-- read/write the same tables concurrently on their own timers. SQLite
-- WAL gives one writer + many readers; writer-writer still serializes,
-- so a long backfill would stall every skill that needs to write
-- during that window. Moving to Postgres removes that ceiling the
-- same way it did for the dispatch write path.
--
-- FTS5 (vault_notes_fts: path/title/content/tags, porter tokenizer,
-- bm25 ranking) has no drop-in Postgres equivalent -- ported here to a
-- generated tsvector column + GIN index (english config; nearest
-- built-in analog to porter stemming) with ts_rank replacing bm25().
-- Content itself (title/content/tags) did not previously live in
-- vault_documents -- FTS5 stored it standalone. Ported into a new
-- vault_notes_fulltext table, one row per vault_documents.path, since
-- Postgres has no separate "virtual table" concept to mirror FTS5's.
--
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS vault_documents (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path            TEXT UNIQUE NOT NULL,
    filename        TEXT NOT NULL,
    category        TEXT,
    size_bytes      BIGINT,
    mtime           TEXT,
    etag            TEXT,
    indexed_at      TEXT NOT NULL,
    tags            TEXT,
    ingest_method   TEXT,
    compile_status  TEXT DEFAULT 'raw'
);
CREATE INDEX IF NOT EXISTS idx_vault_category ON vault_documents(category);
CREATE INDEX IF NOT EXISTS idx_vault_filename ON vault_documents(filename);

-- FTS5 replacement: full note content (title/body/tags), one row per
-- vault path, with a generated tsvector for search + a GIN index for
-- speed. title/tags weighted 'A'/'B', content weighted 'C' (title/tag
-- matches rank above body matches) -- FTS5's bm25 had no field
-- weighting configured, so this is a strict improvement, not parity.
CREATE TABLE IF NOT EXISTS vault_notes_fulltext (
    path            TEXT PRIMARY KEY REFERENCES vault_documents(path) ON DELETE CASCADE,
    title           TEXT,
    content         TEXT,
    tags            TEXT,
    search_vector   tsvector GENERATED ALWAYS AS (
                        setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
                        setweight(to_tsvector('english', coalesce(tags, '')), 'B') ||
                        setweight(to_tsvector('english', coalesce(content, '')), 'C')
                    ) STORED
);
CREATE INDEX IF NOT EXISTS idx_vault_notes_fulltext_search
    ON vault_notes_fulltext USING GIN (search_vector);

CREATE TABLE IF NOT EXISTS entities (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL,
    phones          TEXT,
    category        TEXT NOT NULL,
    source_file     TEXT NOT NULL,
    ingested_at     TEXT NOT NULL,
    UNIQUE(name, source_file)
);
CREATE INDEX IF NOT EXISTS idx_entities_category ON entities(category);

CREATE TABLE IF NOT EXISTS vault_links (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_path     TEXT NOT NULL,
    target          TEXT NOT NULL,
    created_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_vault_links_source ON vault_links(source_path);
CREATE INDEX IF NOT EXISTS idx_vault_links_target ON vault_links(target);

CREATE TABLE IF NOT EXISTS semantic_note_chronology (
    path                TEXT NOT NULL,
    concept_id          TEXT NOT NULL,
    sequence_in_concept INTEGER NOT NULL,
    preceded_by         TEXT,
    note_ts             TEXT NOT NULL,
    PRIMARY KEY (path, concept_id)
);
CREATE INDEX IF NOT EXISTS idx_snchron_concept ON semantic_note_chronology(concept_id);
CREATE INDEX IF NOT EXISTS idx_snchron_preceded_by ON semantic_note_chronology(preceded_by);

CREATE TABLE IF NOT EXISTS semantic_meta (
    key     TEXT PRIMARY KEY,
    value   TEXT
);

CREATE TABLE IF NOT EXISTS semantic_facets (
    id              TEXT PRIMARY KEY,
    pref_label      TEXT,
    definition      TEXT,
    scope_note      TEXT,
    polyhierarchy   INTEGER
);

CREATE TABLE IF NOT EXISTS semantic_concepts (
    id              TEXT PRIMARY KEY,
    facet           TEXT NOT NULL,
    pref_label      TEXT NOT NULL,
    definition      TEXT,
    scope_note      TEXT,
    broader         TEXT,
    in_domain       TEXT,
    source          TEXT,
    entity_subtype  TEXT
);
CREATE INDEX IF NOT EXISTS idx_semantic_concepts_facet ON semantic_concepts(facet);

CREATE TABLE IF NOT EXISTS semantic_labels (
    concept_id      TEXT NOT NULL,
    label           TEXT NOT NULL,
    normalized      TEXT NOT NULL,
    is_preferred    INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_semantic_labels_norm ON semantic_labels(normalized);
CREATE INDEX IF NOT EXISTS idx_semantic_labels_concept ON semantic_labels(concept_id);

CREATE TABLE IF NOT EXISTS semantic_relations (
    source_id   TEXT NOT NULL,
    predicate   TEXT NOT NULL,
    target_id   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_semantic_relations_source ON semantic_relations(source_id);

CREATE TABLE IF NOT EXISTS semantic_agents (
    id                  TEXT PRIMARY KEY,
    pref_label          TEXT,
    kind                TEXT,
    writes_genre        TEXT,
    writes_provenance   TEXT,
    authority           TEXT,
    domains             TEXT
);

CREATE TABLE IF NOT EXISTS semantic_metrics (
    id              TEXT PRIMARY KEY,
    pref_label      TEXT,
    definition      TEXT,
    scope_note      TEXT,
    unit            TEXT,
    grain           TEXT,
    sql             TEXT
);

CREATE TABLE IF NOT EXISTS semantic_note_concepts (
    path        TEXT NOT NULL,
    concept_id  TEXT NOT NULL,
    facet       TEXT NOT NULL,
    rule        TEXT NOT NULL,
    evidence    TEXT NOT NULL,
    is_curated  INTEGER NOT NULL,
    PRIMARY KEY (path, concept_id, rule, evidence)
);
CREATE INDEX IF NOT EXISTS idx_snc_concept ON semantic_note_concepts(concept_id);
CREATE INDEX IF NOT EXISTS idx_snc_path ON semantic_note_concepts(path);
CREATE INDEX IF NOT EXISTS idx_snc_facet ON semantic_note_concepts(facet);

CREATE TABLE IF NOT EXISTS semantic_unmapped_tags (
    tag             TEXT PRIMARY KEY,
    occurrences     INTEGER NOT NULL
);

-- kind: 'evidenced' today; geometric reasoning adds 'geometric' /
-- 'causal' / 'cluster' kinds here per docs/GEOMETRIC_REASONING_DESIGN_2026-09-17.md.
CREATE TABLE IF NOT EXISTS semantic_note_derivations (
    path        TEXT NOT NULL,
    relation    TEXT NOT NULL,
    target      TEXT NOT NULL,
    evidence    TEXT NOT NULL,
    kind        TEXT NOT NULL DEFAULT 'evidenced',
    PRIMARY KEY (path, relation, target, evidence)
);
CREATE INDEX IF NOT EXISTS idx_snd_path ON semantic_note_derivations(path);
CREATE INDEX IF NOT EXISTS idx_snd_relation ON semantic_note_derivations(relation);
CREATE INDEX IF NOT EXISTS idx_snd_target ON semantic_note_derivations(target);
CREATE INDEX IF NOT EXISTS idx_snd_kind ON semantic_note_derivations(kind);
