-- Migration 0056: dispatch chat history (was
-- /var/lib/corporatetraveldc/dispatch-chat.db, a standalone SQLite file
-- opened directly by src/runner/main.py via sqlite3.connect(CHAT_DB_PATH)
-- -- never routed through common.db.conn(), so it sat outside both the
-- original 65-table write-path cutover and the REFERENCE_TABLES set).
--
-- Per the operator directive completing the Postgres cutover ("everything
-- now in the live system should be on Postgres"): this is a live,
-- currently-running table (src/runner/main.py's /api/ask and
-- /api/chat/history routes), not a historical document or retired code,
-- so it moves like the rest of the write path rather than staying SQLite.
--
-- Trivial data volume (0 rows in both the prod and demo runner mounts as
-- of 2026-09-20 -- confirmed live via sqlite3 .schema/count against both
-- /var/lib/corporatetraveldc/dispatch-chat.db and
-- /var/lib/corporatetraveldc-demo/dispatch-chat.db), so no bulk-copy
-- script is needed -- see scripts/migrate-sqlite-to-pg.py's TABLE_PLAN
-- convention for tables that do carry rows.
--
-- ts REAL -> DOUBLE PRECISION directly (not REAL) per the lesson in 0050:
-- SQLite REAL is always 8-byte IEEE-754, so this gets the same fix up
-- front instead of a follow-on widening migration. The CHECK(role IN
-- (...)) constraint carries over unchanged -- Postgres supports CHECK
-- constraints natively, no translation needed.
--
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS chat_messages (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role    TEXT    NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT    NOT NULL,
    ts      DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_chat_ts ON chat_messages(ts);
