-- Migration 0056: demo archive (demo.db) + demo access profiles
-- (demo_access.db) -- the last two LIVE, non-reference SQLite stores
-- outside the main dispatch write path and the second-brain vault index
-- (0055).
--
-- Operator directive 2026-09-20: "Everything now that is in the live
-- system should be on Postgres. Anything that is currently running live
-- should have all of the SQLite references removed unless it is either a
-- historical document or in a retired directory." demo.db (the recorder's
-- raw snapshot archive, 67,331 rows) and demo_access.db (the public-demo
-- password-gate profile store, 7 rows) are both live-read/write every
-- day -- neither is historical or retired, so both move here alongside
-- 0052-0055's reversal of the original "stays SQLite forever" call.
--
-- Table names are prefixed demo_* (demo_snapshots / demo_profiles) rather
-- than reusing the SQLite files' own bare `snapshots` / `profiles` names
-- -- this Postgres instance is one shared namespace for the whole
-- platform (unlike each SQLite file being its own isolated database), and
-- a bare `snapshots` would also be confusable with the UNRELATED
-- `snapshots` table inside scripts/scrub-demo-source.py's sovereign
-- demo-source.db file (a separate, still-SQLite, scrubbed derivative --
-- explicitly out of scope for this migration, see
-- scripts/migrate-demo-to-pg.py's module docstring).
--
-- payload BLOB -> BYTEA (zlib-compressed JSON/prose text, unchanged from
-- the SQLite shape -- see src/demo/db.py for the read/decompress side).
-- captured_at/created_at stay TEXT (ISO-8601), NOT native TIMESTAMPTZ --
-- same convention already established for every other TEXT-timestamp
-- column ported in this migration series (see db_backend.py's
-- _DATETIME_CAST_RE comment): cast at query time (`col::timestamptz` /
-- `col::date`), don't change the column type. compressed/auto_scale/
-- active go to native BOOLEAN (SQLite stored them as INTEGER 0/1;
-- Postgres has a real boolean type and every call site already treats
-- them as truthy/falsy, not as an integer to arithmetic on).
--
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS demo_snapshots (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint     TEXT    NOT NULL,
    captured_at  TEXT    NOT NULL,
    payload      BYTEA   NOT NULL,
    payload_hash TEXT,
    compressed   BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE INDEX IF NOT EXISTS idx_demo_snapshots_ep_time
    ON demo_snapshots(endpoint, captured_at);

CREATE TABLE IF NOT EXISTS demo_profiles (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label         TEXT    NOT NULL,
    password_hash TEXT    NOT NULL,
    salt          TEXT    NOT NULL,
    window_days   INTEGER NOT NULL,
    speed         DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    auto_scale    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TEXT    NOT NULL,
    active        BOOLEAN NOT NULL DEFAULT TRUE
);
