-- Migration 0062: tamper-evident audit log (hash chain + signed checkpoints
-- + signed archive stubs).
--
-- Closes the gap found in docs/ANP_FEDERATION_RESEARCH_2026-09-21.md: the
-- audit_log had no triggers, no rules, and no grant restrictions -- it was
-- append-only by CONVENTION and code path only. Nothing prevented a direct
-- UPDATE/DELETE, and nothing would have detected one after the fact. That is
-- tolerable for one site with one trusted operator; it is not compatible with
-- "provable at every location, for every operator."
--
-- Retention decision (operator, 2026-09-21): audit rows are NOT pruned in
-- place. Instead, anything past a configurable retention horizon is
-- checkpointed, signed, exported off-box (NAS or equivalent), and replaced
-- on-device by a condensed, signed STUB. The stub keeps the audit question
-- answerable -- who held what permissions, who acted, over what window, and
-- the hash/signature proving the exported detail is authentic -- without
-- keeping every row resident. Deleting audit rows with no signed successor
-- is the one thing this design never does.
--
-- pgcrypto is required for digest(). It ships with the official postgres
-- images; if a future deployment lacks it, this migration fails loudly at
-- CREATE EXTENSION rather than silently installing an unhashed trigger.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ── 1. The chain ─────────────────────────────────────────────────────────
-- Each row commits to its predecessor. Any insertion, deletion, or edit of
-- history breaks verification from that point forward.
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS prev_hash TEXT;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS row_hash  TEXT;

-- Actor binding is already present and is deliberately INSIDE the hashed
-- content below: token_prefix is the ctdc_<user>_ prefix, tier is the
-- privilege level, remote_addr is origin. Hashing them means the identity
-- of the actor cannot be altered after the fact without breaking the chain
-- -- which is the actual requirement, not merely recording who it was.
CREATE OR REPLACE FUNCTION audit_log_chain() RETURNS trigger AS $$
DECLARE
    prev TEXT;
BEGIN
    -- Serialize appends. Without this, two concurrent writers (web and
    -- poller are separate containers, both audit) could read the same head
    -- and fork the chain into two branches that each look valid alone.
    -- Transaction-scoped, released at commit. Audit volume is ~150 rows/day,
    -- so the contention cost here is effectively zero.
    PERFORM pg_advisory_xact_lock(hashtext('audit_log_chain'));

    SELECT row_hash INTO prev FROM audit_log ORDER BY id DESC LIMIT 1;
    NEW.prev_hash := COALESCE(prev, '');

    -- id is deliberately NOT hashed: it is IDENTITY-assigned and a rolled
    -- back transaction burns one, so including it would make the chain
    -- depend on gap-free sequence allocation, which Postgres does not
    -- promise. Ordering carries the sequence; content carries the meaning.
    NEW.row_hash := encode(digest(
        NEW.prev_hash                        || '|' ||
        COALESCE(NEW.event_time::text, '')   || '|' ||
        NEW.action                           || '|' ||
        NEW.tier                             || '|' ||
        COALESCE(NEW.token_prefix, '')       || '|' ||
        COALESCE(NEW.remote_addr, '')        || '|' ||
        COALESCE(NEW.detail, '')
    , 'sha256'), 'hex');

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS audit_log_chain_trg ON audit_log;
CREATE TRIGGER audit_log_chain_trg
    BEFORE INSERT ON audit_log
    FOR EACH ROW EXECUTE FUNCTION audit_log_chain();

-- ── 2. Signed checkpoints ────────────────────────────────────────────────
-- A checkpoint pins the chain head at a moment and carries a detached
-- signature over it, using the same agent signing key scripts/sign-manifest.sh
-- already uses. This is what makes the chain externally provable rather than
-- merely internally consistent: without a signature, anyone who can rewrite
-- the table can also recompute every hash.
CREATE TABLE IF NOT EXISTS audit_checkpoints (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TEXT NOT NULL,
    covers_from_id  BIGINT NOT NULL,
    covers_to_id    BIGINT NOT NULL,
    chain_head_hash TEXT NOT NULL,      -- row_hash of covers_to_id
    signature       TEXT NOT NULL,      -- detached ASCII-armored signature
    signing_key_id  TEXT NOT NULL       -- which key signed; honest audit trail
);
CREATE INDEX IF NOT EXISTS idx_audit_checkpoints_range
    ON audit_checkpoints(covers_to_id);

-- ── 3. Archive stubs ─────────────────────────────────────────────────────
-- What stays on-device after a range is exported off-box. Answers the audit
-- questions that matter -- which actors, which privilege tiers, what window,
-- how many events -- plus the digest/signature binding this summary to the
-- exported detail, so the off-box copy can be proven authentic later.
--
-- actors/actions are summaries, not full rows: that is the entire point of
-- the stub. If a specific event needs producing, the archive_uri copy is
-- fetched and verified against archive_sha256.
CREATE TABLE IF NOT EXISTS audit_archive_stubs (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TEXT NOT NULL,
    covers_from_id  BIGINT NOT NULL,
    covers_to_id    BIGINT NOT NULL,
    covers_from_ts  REAL NOT NULL,
    covers_to_ts    REAL NOT NULL,
    row_count       BIGINT NOT NULL,
    actors          TEXT NOT NULL,      -- JSON: {token_prefix: {tier, count}}
    actions         TEXT NOT NULL,      -- JSON: {action: count}
    chain_head_hash TEXT NOT NULL,      -- chain head at covers_to_id
    archive_sha256  TEXT NOT NULL,      -- digest of the exported file
    archive_uri     TEXT,               -- where it went (NAS path / URI)
    signature       TEXT NOT NULL,      -- signature over this stub's content
    signing_key_id  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_archive_stubs_range
    ON audit_archive_stubs(covers_to_id);

-- NOTE -- deliberately NOT done here, and why:
--
-- 1. No REVOKE/GRANT hardening. The dispatch role owns these tables and must
--    INSERT into audit_log; a role split (writer vs owner) is the correct
--    next hardening step but changes the connection model for every
--    container, so it is a separate, deliberate migration.
-- 2. No trigger blocking UPDATE/DELETE on audit_log. The archival process
--    legitimately deletes after signing, so a blanket block would have to be
--    bypassed by the very process that needs it. Detection (the chain) plus
--    a signed successor is the chosen guarantee, not prevention.
-- 3. SQLite divergence: DISPATCH_DB_BACKEND=sqlite remains a supported
--    dev/rollback path and gets NO trigger -- SQLite has no equivalent that
--    survives the same way. Chain columns exist but stay NULL there. That is
--    acceptable for a dev path and unacceptable for production; production is
--    Postgres. Documented rather than silently divergent.
