"""Numbered Postgres DDL migrations for the dispatch write-path schema.

Not imported by any running service -- DISPATCH_DB_BACKEND stays sqlite
by default (see docs/POSTGRES_MIGRATION.md Phase 1) and the sqlite path
still creates its own tables via common.db's init_db_vN() chain, byte for
byte unchanged. This package exists only for scripts/pg_migrate.py to
apply against the Postgres instance ahead of any real cutover.

Provenance: every file here is a mechanical translation of one SQLite
SCHEMA_V* block (from src/common/db.py / src/common/db_swim.py) or one of
the three inline `_ensure_*()` lazy-DDL functions in db.py that predate
the init_db_vN() chain and were never folded into it -- see 0047/0048's
own headers. Reference tables (the 11 bulk-loaded, read-mostly sets
listed in docs/POSTGRES_MIGRATION.md §2) are deliberately NOT here; they
stay SQLite-only forever and are reached through common.db_backend's
ref_conn(), never through this schema.

Translations applied (docs/POSTGRES_MIGRATION.md Appendix A):
  INTEGER PRIMARY KEY AUTOINCREMENT -> INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  unixepoch()                       -> extract(epoch from now())
  ALTER TABLE ... ADD COLUMN        -> ALTER TABLE ... ADD COLUMN IF NOT EXISTS
    (replaces the SQLite duplicate-column-swallow try/except pattern --
    Postgres supports IF NOT EXISTS on ADD COLUMN natively since 9.6)

Timestamp conventions are kept exactly as they are on the SQLite side in
this phase (REAL epoch on legacy tables, TEXT ISO-8601 on SWIM tables) --
deliberate, see docs/POSTGRES_MIGRATION.md §4. Nothing here is TIMESTAMPTZ
except schema_migrations.applied_at, which is new bookkeeping, not a
carried-over column.
"""
