#!/usr/bin/env python3
"""scripts/agent-segmentation/secrets-subset.py -- build a per-GROUP secrets
subset file from the production env files, allowlist-driven, values verbatim.

Two profiles (2026-10-04, team segmentation -- humans and agents in parallel):
    --profile agent   allowlist secrets-allowlist-agent.txt
                      -> /etc/ctdc-agent/agent-secrets.env  root:ctdc-agents 0640
    --profile ops     allowlist secrets-allowlist-ops.txt
                      -> /etc/ctdc-ops/ops-secrets.env      root:ctdc-ops    0640

    sudo python3 scripts/agent-segmentation/secrets-subset.py --profile agent   # write
    python3 scripts/agent-segmentation/secrets-subset.py --profile ops --check  # names only
    python3 scripts/agent-segmentation/secrets-subset.py --profile agent --dry-run

Reads /etc/corporatetraveldc/dispatch.env and dispatch-secrets.env with the
SAME verbatim parser the rest of the platform uses (scripts/lib/
with_dispatch_env.py -- podman --env-file semantics: everything after the first
"=" literally, no quote stripping, no shell). Writes ONLY the variable names
listed in secrets-allowlist.txt to /etc/ctdc-agent/agent-secrets.env, mode
0640, owner root, group ctdc-agent. See docs/AGENT_SEGMENTATION.md Part 2.

Never prints a value: every message is names, counts and paths only. Writing
requires root (the output is root-owned by design, so the operator runs it via
sudo); --check and --dry-run run as anyone who can read the source files.
"""
from __future__ import annotations

import argparse
import grp
import os
import stat
import sys
import tempfile
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(REPO, "scripts", "lib"))
from with_dispatch_env import load as load_env_files  # noqa: E402  (verbatim parser)

DEFAULT_SOURCES = [
    "/etc/corporatetraveldc/dispatch.env",
    "/etc/corporatetraveldc/dispatch-secrets.env",
]
PROFILES = {
    "agent": {"allowlist": os.path.join(HERE, "secrets-allowlist-agent.txt"),
              "out": "/etc/ctdc-agent/agent-secrets.env", "group": "ctdc-agents"},
    "ops":   {"allowlist": os.path.join(HERE, "secrets-allowlist-ops.txt"),
              "out": "/etc/ctdc-ops/ops-secrets.env", "group": "ctdc-ops"},
}
DEFAULT_PROFILE = "agent"
OUT_MODE = 0o640


def read_allowlist(path: str) -> list[tuple[str, bool]]:
    """Return [(NAME, optional), ...] in file order."""
    out: list[tuple[str, bool]] = []
    with open(path, encoding="utf-8") as fh:
        for raw in fh:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            optional = line.endswith("?")
            name = line[:-1] if optional else line
            if not name.isidentifier() or not name.isupper():
                raise SystemExit(f"allowlist: bad variable name on line {line!r}")
            out.append((name, optional))
    return out


def collect(sources: list[str], allowlist: list[tuple[str, bool]]):
    env = load_env_files(sources, {})
    present = {n: env[n] for n, _ in allowlist if n in env}
    missing = [n for n, opt in allowlist if n not in env and not opt]
    absent_optional = [n for n, opt in allowlist if n not in env and opt]
    return present, missing, absent_optional


def report(present, missing, absent_optional, sources) -> int:
    print(f"sources : {', '.join(sources)}")
    print(f"present : {len(present)} -> {' '.join(sorted(present))}")
    if absent_optional:
        print(f"optional, absent: {' '.join(absent_optional)}")
    if missing:
        print(f"MISSING : {' '.join(missing)}")
        return 1
    return 0


def write_subset(present: dict[str, str], out: str, group: str, chown: bool,
                 profile: str = DEFAULT_PROFILE) -> None:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    header = (
        f"# {out} -- GENERATED by scripts/agent-segmentation/secrets-subset.py\n"
        f"# --profile {profile} (group {group}); do not edit by hand.\n"
        f"# generated: {stamp}  names: {len(present)}\n"
        "# Same format rules as dispatch-secrets.env: bare values, no quotes,\n"
        "# never shell-source (use scripts/with-dispatch-env.sh with\n"
        f"# WITH_DISPATCH_ENV_FILES={out}).\n"
    )
    body = "".join(f"{k}={v}\n" for k, v in present.items())
    d = os.path.dirname(out)
    os.makedirs(d, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=f".{profile}-secrets.", dir=d)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(header)
            fh.write(body)
        os.chmod(tmp, OUT_MODE)
        if chown:
            gid = grp.getgrnam(group).gr_gid
            os.chown(tmp, 0, gid)
        os.replace(tmp, out)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--sources", nargs="+", default=DEFAULT_SOURCES,
                    help="env files, later overrides earlier (default: dispatch.env, dispatch-secrets.env)")
    ap.add_argument("--profile", choices=sorted(PROFILES), default=DEFAULT_PROFILE,
                    help="which group's subset: agent (ctdc-agents) or ops (human teammates, ctdc-ops)")
    ap.add_argument("--allowlist", default=None, help="override the profile's allowlist file")
    ap.add_argument("--out", default=None, help="override the profile's output path")
    ap.add_argument("--group", default=None, help="override the profile's group owner")
    ap.add_argument("--check", action="store_true", help="report present/missing names only; write nothing")
    ap.add_argument("--dry-run", action="store_true", help="like --check but also shows the output path/mode")
    ap.add_argument("--no-chown", action="store_true",
                    help="skip chown root:<group> (tests / non-root dry writes to a temp path)")
    args = ap.parse_args(argv)
    prof = PROFILES[args.profile]
    args.allowlist = args.allowlist or prof["allowlist"]
    args.out = args.out or prof["out"]
    args.group = args.group or prof["group"]
    print(f"profile : {args.profile} (group {args.group}, allowlist {os.path.basename(args.allowlist)})")

    for p in args.sources:
        if not os.access(p, os.R_OK):
            print(f"cannot read source {p}", file=sys.stderr)
            return 66
    allow = read_allowlist(args.allowlist)
    present, missing, absent_optional = collect(args.sources, allow)
    rc = report(present, missing, absent_optional, args.sources)

    if args.check:
        return rc
    if args.dry_run:
        print(f"would write: {args.out}  mode {oct(OUT_MODE)}  owner root:{args.group}")
        return rc
    if missing:
        print("refusing to write with required names missing", file=sys.stderr)
        return 1
    chown = not args.no_chown
    if chown and os.geteuid() != 0:
        print("writing the agent subset requires root (output is root-owned); "
              "run via sudo, or pass --no-chown with a non-system --out for a test",
              file=sys.stderr)
        return 77
    if chown:
        try:
            grp.getgrnam(args.group)
        except KeyError:
            print(f"group {args.group} does not exist yet -- run plan.sh shared step 1 first", file=sys.stderr)
            return 78
    write_subset(present, args.out, args.group, chown, args.profile)
    st = os.stat(args.out)
    print(f"wrote {args.out}: {len(present)} names, mode {oct(stat.S_IMODE(st.st_mode))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
