#!/usr/bin/env python3
"""scripts/service-env/generate.py -- per-service scoped SECRET env files.

Duel finding M9 (2026-10-04): every first-party container was handed the whole
/etc/corporatetraveldc/dispatch-secrets.env (59 secret-shaped names), so one
compromised image reached every credential. Each <service>.allowlist here
lists the secret NAMES that service actually reads; this script writes

    /etc/corporatetraveldc/svc/<service>.env   root:corporatetraveldc 0640

containing only those names, values copied VERBATIM (scripts/lib/
with_dispatch_env.load -- podman --env-file semantics, no quoting, no
expansion). The quadlet then mounts dispatch.env (non-secret) plus its own
scoped file instead of dispatch-secrets.env.

  generate.py [--check]              default: report present/missing NAMES only
  generate.py --write [svc ...]      root only; all services when none given
Never prints a value.
"""
from __future__ import annotations

import argparse
import grp
import os
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "lib"))
from with_dispatch_env import load  # noqa: E402

SECRETS = os.environ.get("SERVICE_ENV_SOURCE", "/etc/corporatetraveldc/dispatch-secrets.env")
OUT_DIR = Path(os.environ.get("SERVICE_ENV_OUT", "/etc/corporatetraveldc/svc"))
OUT_GROUP = os.environ.get("SERVICE_ENV_GROUP", "corporatetraveldc")


def read_allowlist(path: Path) -> list[str]:
    names = []
    for raw in path.read_text().splitlines():
        line = raw.split("#", 1)[0].strip()
        if line:
            names.append(line)
    return names


def scoped(source: dict, names: list[str]) -> tuple[dict, list[str]]:
    present = {n: source[n] for n in names if n in source}
    missing = [n for n in names if n not in source]
    return present, missing


def services(selected: list[str]) -> list[Path]:
    al = sorted(HERE.glob("*.allowlist"))
    if selected:
        al = [p for p in al if p.stem in selected]
        unknown = set(selected) - {p.stem for p in al}
        if unknown:
            raise SystemExit(f"unknown service(s): {', '.join(sorted(unknown))}")
    return al


def write_file(path: Path, kv: dict) -> None:
    path.parent.mkdir(mode=0o750, parents=True, exist_ok=True)
    gid = grp.getgrnam(OUT_GROUP).gr_gid
    os.chown(path.parent, 0, gid)
    os.chmod(path.parent, 0o750)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.")
    with os.fdopen(fd, "w") as fh:
        fh.write("# generated by scripts/service-env/generate.py -- do not edit; edit the allowlist\n")
        for k in sorted(kv):
            fh.write(f"{k}={kv[k]}\n")
    os.chown(tmp, 0, gid)
    os.chmod(tmp, 0o640)
    os.replace(tmp, path)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("services", nargs="*")
    a = ap.parse_args(argv)
    if not os.access(SECRETS, os.R_OK):
        print(f"generate: cannot read {SECRETS}", file=sys.stderr)
        return 66
    source = load([SECRETS], {})
    if a.write and os.geteuid() != 0:
        print("generate: --write needs root (sudo)", file=sys.stderr)
        return 77
    rc = 0
    for al in services(a.services):
        names = read_allowlist(al)
        present, missing = scoped(source, names)
        print(f"{al.stem:24s} names={len(names):3d} present={len(present):3d} missing={len(missing)}"
              + (f" -> {' '.join(missing)}" if missing else ""))
        if a.write:
            write_file(OUT_DIR / f"{al.stem}.env", present)
            print(f"  wrote {OUT_DIR / (al.stem + '.env')} (root:{OUT_GROUP} 0640)")
        if missing:
            rc = 1
    print(f"(source has {len(source)} secret names; nothing above is a value)")
    return rc


if __name__ == "__main__":
    sys.exit(main())
